### ISSUE TITLE
lowerBound and upperBound means

### ISSUE THREAD

**Issue by YuanTian1991** [jasminezhoulab/CancerLocator#2]
Hello:

I am not very clear about the meaning of **lowerBound** and **UpperBound** in your function MixModel.java. And what is "nBeta" and "betas" mean in this function?

Many thanks for your answer.

Best
Yuan Tian

**Comment by jasminezhoulab** [comment]
Hi Yuan,

lowerBound and upperBound define the range of possible methylation values of one component (ctDNA), given a methylation value of the mixture, a blood tumor burden (\theta) and the methylation value range of the other component to be [0,1]

nBeta specifies the number of preset beta values (i.e. methylation values) and betas is these beta values. Given numbers of methylated and total CpGs of a CpG cluster, the probability density of the real methylation level is estimated for each of these preset beta values (see function calLogCompoundDens for details)

Hope this helps.

Best,
Shuli Kang

**Comment by YuanTian1991** [comment]
Many Thanks! Now I understand that. ^_^
